// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parks.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksContext))]
    [Migration("20200131194111_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Parks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alerts");

                    b.Property<string>("Info");

                    b.Property<string>("Name");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Alerts = "Rain - 39°F",
                            Info = "39000 State Route 706 E, Ashford, WA 98304",
                            Name = "Mt. Rainier"
                        },
                        new
                        {
                            ParkId = 2,
                            Alerts = "Rain 40°F - FMultiple Closures Due to Weather",
                            Info = "3002 Mt Angeles Rd, Port Angeles, WA 98362",
                            Name = "Olympic"
                        },
                        new
                        {
                            ParkId = 3,
                            Alerts = "Rain - 39°F - State Route 20 Closed for the Season",
                            Info = "North Cascades Highway, North Cascades National Park, WA",
                            Name = "North Cascades"
                        },
                        new
                        {
                            ParkId = 4,
                            Alerts = "Rain - 43°F",
                            Info = "Eastsound, Orcas Island, WA",
                            Name = "Sucia Island"
                        },
                        new
                        {
                            ParkId = 5,
                            Alerts = "Rain - 40°F",
                            Info = "Whidbey Island",
                            Name = "Ebey's Landing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
